modLoader="javafml"
loaderVersion="[${FORGE_LOADER_VERSION},)"
license="${MOD_LICENSE}"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
    modId="${MOD_ID}"
    version="${MOD_VERSION}"
    displayName="${MOD_NAME}"
    updateJSONURL="https://api.modrinth.com/updates/apexcore/forge_updates.json"
    displayURL="https://apexstudios.dev/fantasys-furniture"
    logoFile="banner.png"
    credits="Apex - [Founder, Lead Programmer], FantasyGaming (Viscerus) - [Co-Founder, Artist], RudySPG - [Supporter], TobiSPG - [Supporter, Beta Tester]"
    authors="ApexStudios"
    description="${MOD_DESCRIPTION}"

[[dependencies."${MOD_ID}"]]
	modId="forge"
	mandatory=true
	versionRange="${FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}"]]
	modId="minecraft"
	mandatory=true
	versionRange="${MINECRAFT_FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}"]]
	modId="architectury"
	mandatory=true
	versionRange="${ARCHITECTURY_FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}"]]
	modId="apexcore"
	mandatory=true
	versionRange="${APEXCORE_FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
