modLoader="javafml"
loaderVersion="[${FORGE_LOADER_VERSION},)"
license="GNU General Public License v3.0"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
    modId="${MOD_ID}"
    version="${MOD_VERSION}"
    displayName="${MOD_NAME}"
    updateJSONURL="https://api.modrinth.com/updates/fantasy-furniture/forge_updates.json"
    displayURL="https://apexstudios.dev/fantasys-furniture"
    logoFile="banner.png"
    credits="Apex - [Founder, Lead Programmer], FantasyGaming (Viscerus) - [Co-Founder, Artist], RudySPG - [Supporter], TobiSPG - [Supporter, Beta Tester]"
    authors="ApexStudios"
    description="${MOD_DESCRIPTION}"

[[dependencies.${MOD_ID}]]
	modId="forge"
	mandatory=true
	versionRange="${FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		ignore=true
[[dependencies.${MOD_ID}]]
	modId="minecraft"
	mandatory=true
	versionRange="${MINECRAFT_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		ignore=true
[[dependencies.${MOD_ID}]]
	modId="${APEXCORE_ID}"
	mandatory=false
	versionRange="${APEXCORE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		modrinth="${APEXCORE_ID}"
		curseforge="${APEXCORE_ID}"
[[dependencies.${MOD_ID}]]
	modId="${ARCHITECTURY_ID}"
	mandatory=true
	versionRange="${ARCHITECTURY_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		modrinth="${ARCHITECTURY_DEPENDENCY_ID}"
		curseforge="${ARCHITECTURY_DEPENDENCY_ID}"
[[dependencies.${MOD_ID}]]
	modId="${CLOTH_CONFIG_FORGE_ID}"
	mandatory=true
	versionRange="${CLOTH_CONFIG_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
	[dependencies.${MOD_ID}.custom.mc-publish]
		modrinth="${CLOTH_CONFIG_FABRIC_ID}"
		curseforge="${CLOTH_CONFIG_FABRIC_ID}"
