modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/FantasyFurniture/issues"

[[mods]]
	modId="fantasyfurniture"
	version="${file.jarVersion}"
	displayName="Fantasy's Furniture"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/fantasyfurniture.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Texture Artist"
	authors="Apex, FantasyGaming"
	description="Mod requested by Fantasy which adds varying sets of furniture to your Minecraft world."

[[dependencies.fantasyfurniture]]
	modId="forge"
	mandatory=true
	versionRange="[40,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasyfurniture]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasyfurniture]]
	modId="apexcore"
	mandatory=true
	versionRange="[1.18.2,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasyfurniture]]
	modId="jei"
	mandatory=false
	versionRange="[9.5.+,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasyfurniture]]
	modId="ctm"
	mandatory=false
	versionRange="*" # ctm versions are funky, just allow all versions
	ordering="AFTER"
	side="BOTH"