modLoader="javafml"
loaderVersion="[45,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="fantasyfurniture"
	version="${file.jarVersion}"
	displayName="Fantasy's Furniture"
	updateJSONURL="https://api.modrinth.com/updates/fantasy-furniture/forge_updates.json"
	displayURL="https://www.apexstudios.dev/fantasys-furniture"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Artist"
	authors="ApexStudios"
	description="Adds Fantasy-Themed Furniture & Decorational blocks to the game"

[[dependencies.fantasyfurniture]]
	modId="forge"
	mandatory=true
	versionRange="[45.0.0,46.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		ignore=true
[[dependencies.fantasyfurniture]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.4,1.20)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		ignore=true
[[dependencies.fantasyfurniture]]
	modId="commonality"
	mandatory=true
	versionRange="[6.0.0,7.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		ignore=true
[[dependencies.fantasyfurniture]]
	modId="apexcore"
	mandatory=true
	embedded=true
	versionRange="[9.0.0,10.0.0)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		modrinth="apexcore"
		curseforge="apexcore"
[[dependencies.fantasyfurniture]]
	modId="jei"
	mandatory=false
	versionRange="[13.0.0.0,)"
	ordering="AFTER"
	side="BOTH"
	[dependencies.fantasyfurniture.custom.mc-publish]
		curseforge="jei"
#[[dependencies.fantasyfurniture]]
#	modId="ctm"
#	mandatory=false
#	versionRange="*" # ctm versions are funky, just allow all versions
#	ordering="AFTER"
#	side="BOTH"
#	[dependencies.fantasyfurniture.custom.mc-publish]
#		curseforge="ctm"
