modLoader="javafml"
loaderVersion="${forge_version_range}"
license="All rights reserved"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	# updateJSONURL=""
	# displayURL=""
	# logoFile=""
	# credits=""
	authors="${mod_authors}"
	description=""

[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	ordering="NONE"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="NONE"
	side="BOTH"
