modLoader="javafml"
loaderVersion="${forge_version_range}"
license="GNU General Public License v3.0"
issueTrackerURL="${mod_git_url}/issues"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/fantasyfurniture.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Texture Artist"
	authors="${mod_authors}"
	description="Mod requested by Fantasy which adds varying sets of furniture to your Minecraft world."

[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${forge_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="minecraft"
	mandatory=true
	versionRange="${minecraft_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="${registrator_mod_id}"
	mandatory=true
	versionRange="${registrator_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="${apexcore_mod_id}"
	mandatory=true
	versionRange="${apexcore_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="${jei_mod_id}"
	mandatory=false
	versionRange="${jei_version_range}"
	ordering="AFTER"
	side="BOTH"
[[dependencies.${mod_id}]]
	modId="${ctm_mod_id}"
	mandatory=false
	versionRange="*" # ctm versions are funky, just allow all versions
	ordering="AFTER"
	side="BOTH"