modLoader="javafml"
loaderVersion="[${NEOFORGE_LOADER_VERSION},)"
license="${MOD_LICENSE}"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="${MOD_ID}_nordic"
	version="${MOD_VERSION}"
	displayName="${MOD_NAME} - Nordic Module"
	updateJSONURL="https://api.modrinth.com/updates/fantasy-furniture/forge_updates.json"
	displayURL="https://apexstudios.dev/fantasys-furniture"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="${MOD_NAME} - Nordic Module"
	displayTest="MATCH_VERSION"

[features."${MOD_ID}"]
	javaVersion="${JAVA_VERSION}"

[[dependencies."${MOD_ID}_nordic"]]
	modId="forge"
	mandatory=true
	versionRange="${NEOFORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_nordic"]]
	modId="minecraft"
	mandatory=true
	versionRange="${MINECRAFT_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_nordic"]]
	modId="${APEXCORE_ID}"
	mandatory=true
	versionRange="${APEXCORE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_nordic"]]
	modId="${MOD_ID}"
	mandatory=true
	versionRange="[${MOD_VERSION},)"
	ordering="AFTER"
	side="BOTH"
