modLoader="javafml"
loaderVersion="[${MCFORGE_LOADER_VERSION},)"
license="${MOD_LICENSE}"
issueTrackerURL="https://discord.apexstudios.dev/"

[[mods]]
	modId="${MOD_ID}_venthyr"
	version="${MOD_VERSION}"
	displayName="${MOD_NAME} - Venthyr"
	updateJSONURL="https://api.modrinth.com/updates/${MOD_ID}/forge_updates.json"
	displayURL="https://apexstudios.dev/${MOD_ID}"
	logoFile="banner.png"
	credits="Apex - Programming"
	authors="ApexStudios"
	description="Venthyr Furniture Set module for ${MOD_NAME}"
	displayTest="MATCH_VERSION"

[features."${MOD_ID}_venthyr"]
	javaVersion="${JAVA_VERSION}"

[[dependencies."${MOD_ID}_venthyr"]]
	modId="forge"
	mandatory=true
	versionRange="${MCFORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_venthyr"]]
	modId="minecraft"
	mandatory=true
	versionRange="${MINECRAFT_FORGE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_venthyr"]]
	modId="${APEXCORE_ID}"
	mandatory=true
	versionRange="${APEXCORE_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_venthyr"]]
	modId="${MOD_ID}"
	mandatory=true
	versionRange="${MOD_VERSION}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_venthyr"]]
	modId="${JEI_ID}"
	mandatory=false
	versionRange="${JEI_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"
[[dependencies."${MOD_ID}_venthyr"]]
	modId="${REI_ID}"
	mandatory=false
	versionRange="${REI_VERSION_RANGE}"
	ordering="AFTER"
	side="BOTH"